SELECT * FROM USUARIOS;

SELECT MAX(SALDO) FROM USUARIOS WHERE SEXO = "M";

SELECT NOMBRE, TELEFONO FROM USUARIOS WHERE MARCA = "NOKIA" OR MARCA = "BLACKBERRY" OR MARCA = "SONY";

SELECT COUNT(ID) FROM USUARIOS WHERE SALDO = 0 OR ACTIVO = 0;

SELECT TELEFONO FROM USUARIOS WHERE SALDO < 301;

SELECT SUM(SALDO) FROM USUARIOS WHERE COMPANIA = "NEXTEL";

SELECT COMPANIA, COUNT(ID) FROM USUARIOS GROUP BY COMPANIA;

SELECT NIVEL, COUNT(ID) FROM USUARIOS GROUP BY NIVEL;

SELECT EMAIL FROM USUARIOS WHERE EMAIL LIKE "%gmail.com";

SELECT NOMBRE, TELEFONO, MARCA FROM USUARIOS WHERE MARCA = "LG" OR MARCA = "SAMSUNG" OR MARCA = "MOTOROLA";

SELECT NOMBRE, TELEFONO, MARCA FROM USUARIOS WHERE MARCA != "LG" AND MARCA != "SAMSUNG";

SELECT USUARIO, TELEFONO FROM USUARIOS WHERE COMPANIA = "IUSACELL";

SELECT USUARIO, TELEFONO FROM USUARIOS WHERE COMPANIA != "TELCEL";

SELECT AVG(SALDO) FROM USUARIOS WHERE MARCA = "NOKIA";

SELECT USUARIO, TELEFONO FROM USUARIOS WHERE COMPANIA = "IUSACELL" OR COMPANIA = "AXEL";

SELECT EMAIL FROM USUARIOS WHERE EMAIL NOT LIKE "%yahoo%";

SELECT USUARIO, TELEFONO FROM USUARIOS WHERE COMPANIA != "TELCEL" AND COMPANIA != "IUSACELL";

SELECT USUARIO, TELEFONO FROM USUARIOS WHERE COMPANIA = "UNEFON";

SELECT MARCA FROM USUARIOS GROUP BY MARCA order by marca asc;

SELECT COMPANIA FROM USUARIOS GROUP BY COMPANIA;

SELECT USUARIO FROM USUARIOS WHERE NIVEL = 0 OR NIVEL = 2;

SELECT AVG(SALDO) FROM USUARIOS WHERE MARCA = "LG";

SELECT USUARIO  FROM USUARIOS WHERE NIVEL = 1 OR NIVEL = 3;

SELECT NOMBRE, TELEFONO, MARCA FROM USUARIOS WHERE MARCA != "BLACKBERRY";

SELECT USUARIO FROM USUARIOS WHERE NIVEL = 3;

SELECT USUARIO FROM USUARIOS WHERE NIVEL = 0;

SELECT USUARIO FROM USUARIOS WHERE NIVEL = 1;

SELECT SEXO, COUNT(ID) FROM USUARIOS GROUP BY SEXO;

SELECT USUARIO, TELEFONO FROM USUARIOS WHERE COMPANIA = "AT%T";

SELECT COMPANIA FROM USUARIOS GROUP BY COMPANIA ORDER BY COMPANIA DESC;

SELECT USUARIO FROM USUARIOS WHERE ACTIVO = 0;

SELECT TELEFONO FROM USUARIOS WHERE SALDO = 0;

SELECT MIN(SALDO) FROM USUARIOS WHERE SEXO = "H";

SELECT TELEFONO, SALDO FROM USUARIOS WHERE SALDO > 300;

SELECT MARCA, COUNT(ID) FROM USUARIOS GROUP BY MARCA;

SELECT NOMBRE, TELEFONO FROM USUARIOS WHERE MARCA != "LG";

SELECT COMPANIA FROM USUARIOS GROUP BY COMPANIA ORDER BY COMPANIA ASC;

SELECT SUM(SALDOS) FROM USUARIOS WHERE COMPANIA = "UNEFON";

SELECT EMAIL FROM USUARIOS WHERE EMAIL LIKE "%hotmail%";

SELECT NOMBRE FROM USUARIOS WHERE SALDO  = 0 OR ACTIVO = 0;

SELECT USUARIO, TELEFONO FROM USUARIOS WHERE COMPANIA = "IUSACELL" OR COMPANIA = "TELCEL";

SELECT MARCA FROM USUARIOS GROUP BY MARCA ORDER BY MARCA ASC;